title: Thomas Queste
email: tom@tomsquest.com
description: >-
  Tom's Quest: Software development insights, productivity tips, and engaging reads by a passionate engineer.
baseurl: ""
url: https://www.tomsquest.com
# author is used by jekyll-feeds
author:
  name: Thomas Queste
twitter_username: thomasqueste
github_username: tomsquest
sass:
  style: compressed
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:title/
feed:
  path: /atom.xml
plugins:
  - jekyll-feed
  - jekyll-sitemap
