baseURL: "https://www.tomsquest.com/"
publishDir: docs
languageCode: "en-us"
title: "Thomas Queste's blog"
permalinks:
  blog: /blog/:year/:month/:slug/
disqusShortname: tomsquest
pygmentsCodeFences: true
enableGitInfo: true
rssLimit: 20
outputs:
  home: ["HTML", "RSS", "ATOM"]
mediaTypes:
  application/atom+xml:
    suffixes: ["xml"]
outputFormats:
  ATOM:
    mediaType: application/atom+xml
    baseName: atom
    isPlainText: false
disableKinds:
  - taxonomy
  - taxonomyTerm
enableRobotsTXT: true
googleAnalytics: UA-5368525-1
