#!/bin/bash
set -euo pipefail

#
# This script crawls the local site to check for broken links.
# Source: https://medium.com/@stripedpurple/finding-404s-in-your-site-with-wget-8d32e8034217
#

# go to project root
cd "$(git rev-parse --show-toplevel)"

url="http://localhost:4000"
log_file="crawl.log"

echo "Running wget --spider on $url..."
set +e
wget --spider -o "$log_file" --recursive -p "$url"
set -e

num_404s=$(grep -c " 404 " "$log_file" || true)
echo "Found $num_404s 404s."

if [ "$num_404s" -gt 0 ]; then
    echo "Found 404s the following errors:"
    grep -B2 " 404 " "$log_file" || true
fi

echo "Done."
echo "Logs stored in $log_file for more details."